spring.application.name=server

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/momentum_war
spring.datasource.username=postgres
spring.datasource.password=password

# Schema Initialization
spring.sql.init.mode=always

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
